spring:
  application:
    name: movie-client-ui

server:
  port: 8081

movie-server:
  host: localhost
  rest:
    port: 8080

management:
  endpoints:
    web:
      exposure.include: health
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: rsocket-tcp

movie-server:
  rsocket:
    port: 7000

---
spring:
  config:
    activate:
      on-profile: rsocket-websocket

movie-server:
  rsocket:
    mapping-path: /rsocket
