spring:
  application:
    name: movie-server
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/moviedb

management:
  endpoints:
    web:
      exposure.include: health, info
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: rsocket-tcp
  rsocket:
    server:
      transport: tcp
      port: 7000

---
spring:
  profiles: rsocket-websocket
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket