spring:
  application:
    name: movie-server

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: rsocket-tcp
  rsocket:
    server:
      transport: tcp
      port: 7000

---
spring:
  profiles: rsocket-websocket
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket