spring:
  application:
    name: movie-client
  main:
    web-application-type: none

movie-server:
  host: localhost
  rest:
    port: 8080
  rsocket:
    port: 7000

logging:
  level:
    root: error
